# Generated by Django 4.2.6 on 2023-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'target_url',
                    models.CharField(
                        max_length=1354, verbose_name='target url'
                    ),
                ),
                (
                    'shortened_url',
                    models.CharField(
                        default='Y-CDALTQ',
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name='shortened_url',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created at'
                    ),
                ),
            ],
        ),
    ]
