# Generated by Django 4.2.6 on 2023-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('urls', '0002_alter_url_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(
                max_length=8, unique=True, verbose_name='shortened_url'
            ),
        ),
    ]
